###

POST http://localhost:3001/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "nombre": "Luis",
    "apellido": "Pacheco",
    "telefono": "310 500 0000",
    "email": "Luis@example.com",
    "img": "imgLuis"
}



###
GET http://localhost:3001/api/usuarios HTTP/1.1

###
DELETE http://localhost:3001/api/usuarios HTTP/1.1
{
    "__id":"64168172728e27da12a67e39"
}
